#!/usr/bin/env bash
#
# Deploy script

set -e

docker stop $(docker ps -aq) || true
docker rm $(docker ps -aq) || true

# run the new container
cd "/opt/balancebot"
docker run --restart=always -v $(pwd)/config:/srv/app/config -v $(pwd)/db:/srv/app/db -d jaredallard/balancebot:v1 node index.js